version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: TaciTalkDB
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/hberumengovea/Downloads/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis_net

networks:
  redis_net:

volumes:
  redis_data:
